services:
  front:
    container_name: front
    hostname: front
    build:
      context: ../front
      dockerfile: ./docker/Dockerfile.dev
    entrypoint: ["sh", "-c", "npm install && npm run dev"]
    env_file:
      - ../front/.env
    volumes:
      - ../front:/app
    ports:
      - "4321:4321"
    stdin_open: true
    tty: true

  back:
    container_name: back
    hostname: back
    build:
      context: ../back
      dockerfile: ./docker/Dockerfile.dev
    entrypoint:
      [
        "sh",
        "-c",
        "pip install --no-cache-dir -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload",
      ]
    env_file:
      - ../back/.env
    volumes:
      - ../back:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
